export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: "shadcn-docs-nuxt",
      description:
        "The NixOS Config that I wrote to make your system as you as you can be, all the time.",
    },
    theme: {
      customizable: true,
      color: "zinc",
      radius: 0.5,
    },
    banner: {
      enable: true,
      showClose: true,
      content: "Join me on Discord",
      to: "https://discord.gg/ajsbasement",
      target: "_blank",
      border: true,
    },
    header: {
      title: "NixOS Config Docs",
      showTitle: true,
      darkModeToggle: true,
      languageSwitcher: {
        enable: false,
        triggerType: "icon",
        dropdownType: "select",
      },
      logo: {
        light: "https://assets.awfixer.me/moody.gif",
        dark: "https://assets.awfixer.me/moody.gif",
      },
      nav: [
        {
          title: "Docs",
          links: [
            {
              title: "Discord",
              to: "https://discord.gg/ajsbasement",
              description: "Start building your document with shadcn-docs-nuxt",
              icon: "simple-icons:discord",
            },
            {
              title: "Github",
              to: "https://github.com/awfixers-stuff/nixos-config",
              description:
                "Explore available UI components and usage examples.",
              icon: "lucide:github",
            },
            {
              title: "Patreon",
              to: "https://patreon.com/awfixer",
              description: "Discover the configurations and exposed APIs.",
              target: "_self",
            },
          ],
        },
      ],
      links: [
        {
          icon: "lucide:coffee",
          to: "https://ko-fi.com/awfixer",
          target: "_blank",
        },
        {
          icon: "lucide:github",
          to: "https://github.com/awfixers-stuff",
          target: "_blank",
        },
      ],
    },
    aside: {
      useLevel: true,
      collapse: false,
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: "lucide:clipboard",
      editLink: {
        enable: true,
        pattern:
          "https://github.com/ZTL-UwU/shadcn-docs-nuxt/edit/main/www/content/:path",
        text: "Edit this page",
        icon: "lucide:square-pen",
        placement: ["docsFooter"],
      },
      backToTop: true,
      codeIcon: {
        "package.json": "vscode-icons:file-type-node",
        "tsconfig.json": "vscode-icons:file-type-tsconfig",
        ".npmrc": "vscode-icons:file-type-npm",
        ".editorconfig": "vscode-icons:file-type-editorconfig",
        ".eslintrc": "vscode-icons:file-type-eslint",
        ".eslintrc.cjs": "vscode-icons:file-type-eslint",
        ".eslintignore": "vscode-icons:file-type-eslint",
        "eslint.config.js": "vscode-icons:file-type-eslint",
        "eslint.config.mjs": "vscode-icons:file-type-eslint",
        "eslint.config.cjs": "vscode-icons:file-type-eslint",
        ".gitignore": "vscode-icons:file-type-git",
        "yarn.lock": "vscode-icons:file-type-yarn",
        ".env": "vscode-icons:file-type-dotenv",
        ".env.example": "vscode-icons:file-type-dotenv",
        ".vscode/settings.json": "vscode-icons:file-type-vscode",
        nuxt: "vscode-icons:file-type-nuxt",
        ".nuxtrc": "vscode-icons:file-type-nuxt",
        ".nuxtignore": "vscode-icons:file-type-nuxt",
        "nuxt.config.js": "vscode-icons:file-type-nuxt",
        "nuxt.config.ts": "vscode-icons:file-type-nuxt",
        "nuxt.schema.ts": "vscode-icons:file-type-nuxt",
        "tailwind.config.js": "vscode-icons:file-type-tailwind",
        "tailwind.config.ts": "vscode-icons:file-type-tailwind",
        vue: "vscode-icons:file-type-vue",
        ts: "vscode-icons:file-type-typescript",
        tsx: "vscode-icons:file-type-typescript",
        mjs: "vscode-icons:file-type-js",
        cjs: "vscode-icons:file-type-js",
        js: "vscode-icons:file-type-js",
        jsx: "vscode-icons:file-type-js",
        md: "vscode-icons:file-type-markdown",
        mdc: "vscode-icons:file-type-markdown",
        css: "vscode-icons:file-type-css",
        py: "vscode-icons:file-type-python",
        npm: "vscode-icons:file-type-npm",
        pnpm: "vscode-icons:file-type-pnpm",
        npx: "vscode-icons:file-type-npm",
        yarn: "vscode-icons:file-type-yarn",
        bun: "vscode-icons:file-type-bun",
        yml: "vscode-icons:file-type-light-yaml",
        json: "vscode-icons:file-type-json",
        terminal: "lucide:terminal",
      },
    },
    footer: {
      border: true,
      credits: "Copyright © 2025 AWFixer and Friends",
      links: [
        {
          icon: "lucide:heart",
          title: "Sponsor Me",
          to: "https://ko-fi.com/awfixer",
          target: "_blank",
        },
        {
          icon: "lucide:twitter",
          to: "https://x.com/awfixer",
          target: "_blank",
        },
        {
          icon: "simple-icons:discord",
          to: "https://discord.gg/ajsbasement",
          target: "_blank",
        },
        {
          icon: "lucide:github",
          to: "https://github.com/awfixers-stuff",
          target: "_blank",
        },
      ],
    },
    toc: {
      enable: true,
      links: [
        {
          title: "Star on GitHub",
          icon: "lucide:star",
          to: "https://github.com/awfixers-stuff/nixos-config",
          target: "_blank",
        },
        {
          title: "Create Issues",
          icon: "lucide:circle-dot",
          to: "https://github.com/awfixers-stuff/nixos-config/issues",
          target: "_blank",
        },
      ],
    },
    search: {
      enable: true,
      inAside: false,
    },
  },
});
